name: Mirror to drupal.org
on:
  push:
    branches: [1.0.x]
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.drupalcode.org/project/entity_metrics"
      env:
        FOLLOW_TAGS: "true"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "git.drupal.org"
        GITLAB_USERNAME: "foo"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "119035"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
